import Role from "@/models/Role";

async function initDefaultRoles() {
  const defaultRoles = [
    {
      name: 'admin',
      description: 'System Administrator with full access',
      isDefault: true,
      isActive: true,
      // Permissions will be auto-generated by pre-save hook
    },
    {
      name: 'hr',
      description: 'Human Resources Manager',
      isDefault: true,
      isActive: true,
    },
    {
      name: 'employee',
      description: 'Regular Employee',
      isDefault: true,
      isActive: true,
    },
    {
      name: 'accounts',
      description: 'Accounts Department',
      isDefault: true,
      isActive: true,
    },
    {
      name: 'support',
      description: 'Customer Support',
      isDefault: true,
      isActive: true,
    },
    {
      name: 'marketing',
      description: 'Marketing Department',
      isDefault: true,
      isActive: true,
    },
  ];

  for (const roleData of defaultRoles) {
    const existingRole = await Role.findOne({ name: roleData.name });
    if (!existingRole) {
      await Role.create(roleData);
      console.log(`Created role: ${roleData.name}`);
    }
  }
}